### PR TITLE
Add Bootvar.args, which emulates Sys.argv

### PR DESCRIPTION
**Pull request by Drup**
At the moment, I have this piece of code in functoria,
I would prefer it to be here (as it could, at term, be reimplemented more decently).

cc @samoth

### CODE REVIEW

**Comment by djs55** [comment]
I think emulating `Sys.argv` is a good idea -- this would certainly help me (and people like @jonludlam) port some code to mirage and hence to unikernels.

Does functoria hide the difference between `Bootvar.argv` and `Sys.argv` so my app can remain portable?

**Comment by Drup** [comment]
> Does functoria hide the difference between Bootvar.argv and Sys.argv so my app can remain portable?

Yes.

**Comment by MagnusS** [comment]
My only concern with this is that it adds "-" and "--" in front of the variables automatically to make the key/value pairs compatible with command line options. I think it would be a better solution to be able to reuse the Unix command line directly with Bootvar, so that you could just copy the command line options from Unix into the "extra=" field. Any opinions on this? (see also discussion in #4). To do this we would also have to fix the bootvar parameter parsing to support space and quotes.

**Comment by Drup** [comment]
> Any opinions on this?

Not really. To be honest, I don't really care which way it's implemented as long as the function is available. ;)

**Comment by MagnusS** [comment]
Ok - I guess this would work fine without the added "-" and "--" as well, as long as they are included in the command line sent as a boot parameter? E.g. using the format `--key=value -k=v` would work with cmdliner, using `key=value k=v` wouldn't. Or do you need it to always be compatible?

**Comment by samoht** [comment]
I think it's better to have a sane command-line interface (eg. where keys are prefixed by `--`). Regarding the quoting issue, it is best to rely on `Cmdliner` wich does already that for us. The only remaining issue to convert these key/values pairs into the extra parameters for the `xl` files, and this can be done fairly easily later I think. So I'll merge this, and we can improve the rest later on.

**Pull request merged**
